apiVersion: v1
kind: Secret
metadata:
  name: nvd-api-key-secret
  namespace: security-tools # Use if you created the namespace
type: Opaque
stringData:
  # Replace with your actual NVD API Key
  api_key: "YOUR_NVD_API_KEY_HERE_OR_LEAVE_BLANK_IF_NONE"